import { useEffect, useState } from 'react';
import { supabase } from '../supabase/supabaseClient';

const getDeckLists = async ({
  league_id,
}: {
  league_id: number;
}): Promise<
  { id: number; name: string; moxfield_id: string; discord_name: string }[]
> => {
  const query = supabase
    .from('decks_with_username')
    .select('id, name, moxfield_id, discord_name, discord_username')
    .eq('league_id', league_id);

  const { data: decks, error } = await query;

  if (error) {
    console.error(error);
  }

  // @ts-expect-error --  Ignore due to error around autogenerated types
  return decks || [];
};

const useGetDeckLists = ({ league_id }: { league_id: number }) => {
  const [rows, setRows] = useState<
    { name: string; moxfield_id: string; discord_name: string }[]
  >([]);

  useEffect(() => {
    getDeckLists({ league_id }).then((decks) => {
      setRows(decks);
    });

  }, [league_id]);
  return rows;
};

export default useGetDeckLists;
