import { useEffect, useState } from 'react';
import { supabase } from './supabase/supabaseClient';
import NavBar from './NavBar';
import { DataGrid, GridColDef, GridToolbar } from '@mui/x-data-grid';
import { useMediaQuery, useTheme, Link } from '@mui/material';

const getDeckLists = async ({
  league_id,
}: {
  league_id: number;
}): Promise<
  { id: number; name: string; moxfield_id: string; discord_name: string }[]
> => {
  const query = supabase
    .from('decks_with_username')
    .select('id, name, moxfield_id, discord_name, discord_username')
    .eq('league_id', league_id);

  const { data: decks, error } = await query;

  if (error) {
    console.error(error);
  }

  // @ts-expect-error --  Ignore due to error around autogenerated types
  return decks || [];
};

const columns: GridColDef[] = [
  { field: 'discord_name', headerName: 'Name', flex: 0.5 },
  { field: 'discord_username', headerName: 'Discord Username', flex: 0.5 },
  {
    field: 'name',
    headerName: 'Moxfield Deck Name',
    flex: 1,
    renderCell: (row) => {
      return (
        <Link
          variant="body1"
          href={`https://www.moxfield.com/decks/${row.row.moxfield_id}`}
          rel="noref"
          target="_blank"
        >
          {row.value}
        </Link>
      );
    },
  },
];

function DeckList() {
  const theme = useTheme();
  const largeScreen = useMediaQuery(theme.breakpoints.up('sm'));
  const [rows, setRows] = useState<
    { name: string; moxfield_id: string; discord_name: string }[]
  >([]);
  // Todo Make League Id Dynamic
  const [leagueId] = useState<number>(1);
  useEffect(() => {
    getDeckLists({ league_id: leagueId }).then((decks) => {
      setRows(decks);
    });
  }, []);

  return (
    <>
      <NavBar />
      <div style={{ height: '90vh', width: '100%' }}>
        <DataGrid
          rows={rows}
          columns={columns}
          slots={{ toolbar: GridToolbar }}
          slotProps={{
            toolbar: {
              showQuickFilter: true,
            },
          }}
          disableDensitySelector
          disableRowSelectionOnClick
          initialState={{
            columns: {
              columnVisibilityModel: {
                oracle_text: false,
                colors: false,
                // only show this by default on large screens
                discord_username: largeScreen,
              },
            },
          }}
        />
      </div>
    </>
  );
}

export default DeckList;
